name: build
on:
  push:
    branches:
      - "master"
  pull_request:
jobs:
  build:
    name: ğŸ”¨ Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¨ Checkout
        uses: actions/checkout@v3
      - name: ğŸ§© Install dependencies
        run: go get ./...
      - name: âœ… go vet
        run: go vet ./...
  docker:
    name: ğŸ³ Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: 1ï¸âƒ£ Checkout
        uses: actions/checkout@v3
      -
        name: 2ï¸âƒ£ Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: 3ï¸âƒ£ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: 4ï¸âƒ£ Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: 5ï¸âƒ£ Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: modaniru/tgf-image-generator:latest
